<?php
/**
 * Content type registration.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class CYWater_Content_Types {
	private const CAPABILITY_TYPES = array(
		'cyw_event'      => array( 'cyw_event', 'cyw_events' ),
		'cyw_award'      => array( 'cyw_award', 'cyw_awards' ),
		'cyw_board_role' => array( 'cyw_board_role', 'cyw_board_roles' ),
	);

	public static function register() {
		add_action( 'init', array( __CLASS__, 'register_content_types' ) );
		add_action( 'init', array( __CLASS__, 'register_meta' ) );
		add_action( 'pre_get_posts', array( __CLASS__, 'order_archives' ) );
		add_filter( 'tribe_tickets_post_types', array( __CLASS__, 'ticket_post_types' ) );
	}

	/**
	 * Keep ticketing isolated to the CYWater event record.
	 *
	 * Event Tickets defaults to pages and its own calendar post type. CYWater
	 * already owns the public event model, so enabling any other post type would
	 * create a second, confusing editorial surface.
	 *
	 * @return array<int, string>
	 */
	public static function ticket_post_types() {
		return array( 'cyw_event' );
	}

	public static function register_content_types() {
		register_post_type(
			'cyw_event',
			array(
				'labels'          => self::labels( 'Event', 'Events' ),
				'public'          => true,
				'show_in_rest'    => true,
				'has_archive'     => 'events',
				'rewrite'         => array( 'slug' => 'events' ),
				'menu_icon'       => 'dashicons-calendar-alt',
				'supports'        => array( 'title', 'editor', 'excerpt', 'thumbnail', 'revisions', 'custom-fields' ),
				'capability_type' => self::CAPABILITY_TYPES['cyw_event'],
				'map_meta_cap'    => true,
			)
		);

		register_taxonomy(
			'cyw_event_type',
			'cyw_event',
			array(
				'labels'            => array( 'name' => 'Event types', 'singular_name' => 'Event type' ),
				'public'            => true,
				'show_in_rest'      => true,
				'hierarchical'      => true,
				'show_admin_column' => true,
				'rewrite'           => array( 'slug' => 'event-type' ),
			)
		);

		register_post_type(
			'cyw_award',
			array(
				'labels'          => self::labels( 'Award record', 'Award records' ),
				'public'          => true,
				'show_in_rest'    => true,
				'has_archive'     => 'awards',
				'rewrite'         => array( 'slug' => 'awards' ),
				'menu_icon'       => 'dashicons-awards',
				'supports'        => array( 'title', 'editor', 'excerpt', 'thumbnail', 'revisions', 'custom-fields' ),
				'capability_type' => self::CAPABILITY_TYPES['cyw_award'],
				'map_meta_cap'    => true,
			)
		);

		register_post_type(
			'cyw_board_role',
			array(
				'labels'             => self::labels( 'Board role', 'Board roles' ),
				'public'             => false,
				'publicly_queryable' => false,
				'show_ui'            => true,
				'show_in_rest'       => false,
				'menu_icon'          => 'dashicons-groups',
				'supports'           => array( 'title', 'editor', 'thumbnail', 'revisions' ),
				'capability_type'    => self::CAPABILITY_TYPES['cyw_board_role'],
				'map_meta_cap'       => true,
			)
		);

		// Keep the public archive roots stable across hosts and rewrite engines.
		add_rewrite_rule( '^events/?$', 'index.php?post_type=cyw_event', 'top' );
		add_rewrite_rule( '^awards/?$', 'index.php?post_type=cyw_award', 'top' );
	}

	private static function labels( $singular, $plural ) {
		return array(
			'name'          => $plural,
			'singular_name' => $singular,
			'add_new_item'  => 'Add new ' . strtolower( $singular ),
			'edit_item'     => 'Edit ' . strtolower( $singular ),
			'view_item'     => 'View ' . strtolower( $singular ),
			'search_items'  => 'Search ' . strtolower( $plural ),
		);
	}

	/**
	 * Keep the association-owned Administrator able to recover every CYWater
	 * editorial object while custom staff roles receive only their assigned
	 * primitive capabilities.
	 */
	public static function grant_administrator_capabilities() {
		$administrator = get_role( 'administrator' );
		if ( ! $administrator instanceof WP_Role ) {
			return;
		}

		foreach ( self::administrator_capabilities() as $capability ) {
			if ( ! $administrator->has_cap( $capability ) ) {
				$administrator->add_cap( $capability );
			}
		}
	}

	/**
	 * Primitive capabilities generated by WordPress when map_meta_cap is true.
	 * The singular edit/read/delete capabilities remain meta capabilities and
	 * must not be assigned directly to roles.
	 *
	 * @return array<int, string>
	 */
	public static function administrator_capabilities() {
		$capabilities = array();
		foreach ( self::CAPABILITY_TYPES as $types ) {
			$plural = $types[1];
			foreach (
				array(
					"edit_{$plural}",
					"edit_others_{$plural}",
					"publish_{$plural}",
					"read_private_{$plural}",
					"delete_{$plural}",
					"delete_private_{$plural}",
					"delete_published_{$plural}",
					"delete_others_{$plural}",
					"edit_private_{$plural}",
					"edit_published_{$plural}",
					"create_{$plural}",
				) as $capability
			) {
				$capabilities[] = $capability;
			}
		}

		return array_values( array_unique( $capabilities ) );
	}

	/**
	 * Authorize metadata against the concrete object, allowing WordPress to map
	 * edit_post to the correct Event, Award, or Board primitive capabilities.
	 */
	public static function can_edit_post_meta( $allowed, $meta_key, $post_id ) {
		return $post_id && current_user_can( 'edit_post', $post_id );
	}

	public static function register_meta() {
		$public_fields = array(
			'page'      => array( 'eyebrow', 'hero_title', 'lead', 'contact_email', 'mailing_address' ),
			'post'      => array( 'visual_title', 'visual_year', 'source_image', 'source_url', 'source_id' ),
			'cyw_event' => array( 'start_date', 'end_date', 'date_label', 'location', 'format', 'attendees', 'image_alt', 'status', 'source_image', 'source_url', 'source_id' ),
			'cyw_award' => array( 'year', 'recipient', 'paper_title', 'journal', 'applications', 'chair', 'source_id' ),
		);

		foreach ( $public_fields as $post_type => $keys ) {
			foreach ( $keys as $key ) {
				$sanitizer = 'sanitize_text_field';
				if ( in_array( $key, array( 'year', 'applications' ), true ) ) {
					$sanitizer = 'absint';
				} elseif ( 'contact_email' === $key ) {
					$sanitizer = 'sanitize_email';
				} elseif ( 'mailing_address' === $key ) {
					$sanitizer = 'sanitize_textarea_field';
				}
				register_post_meta(
					$post_type,
					'_cyw_' . $key,
					array(
						'type'              => in_array( $key, array( 'year', 'applications' ), true ) ? 'integer' : 'string',
						'single'            => true,
						'show_in_rest'      => true,
						'sanitize_callback' => $sanitizer,
						'auth_callback'     => array( __CLASS__, 'can_edit_post_meta' ),
					)
				);
			}
		}

		foreach ( array( 'person_name', 'affiliation', 'term', 'order', 'confirmed_public', 'source_id' ) as $key ) {
			register_post_meta(
				'cyw_board_role',
				'_cyw_' . $key,
				array(
					'type'          => in_array( $key, array( 'order', 'confirmed_public' ), true ) ? 'integer' : 'string',
					'single'        => true,
					'show_in_rest'  => false,
					'auth_callback' => array( __CLASS__, 'can_edit_post_meta' ),
				)
			);
		}
	}

	public static function order_archives( $query ) {
		if ( is_admin() || ! $query->is_main_query() ) {
			return;
		}
		if ( $query->is_post_type_archive( 'cyw_event' ) ) {
			$query->set( 'orderby', 'date' );
			$query->set( 'order', 'DESC' );
			$query->set( 'posts_per_page', 20 );
		}
		if ( $query->is_post_type_archive( 'cyw_award' ) ) {
			$query->set( 'orderby', 'date' );
			$query->set( 'order', 'DESC' );
			$query->set( 'posts_per_page', 30 );
		}
	}
}
